INSERT INTO category (id, parent_id, locale, position, title, description, color, image, imagethumb, visible, trusted) VALUES
(1, NULL, 'uk_UA', 0, 'ТТУ', 'Тяжкі тілесні ушкодження', 'ff0000', NULL, NULL, true, false),
(2, NULL, 'uk_UA', 1, 'Вбивства', 'Вбивства', 'd12323', NULL, NULL, true, false),
(3, NULL, 'uk_UA', 2, 'Розбій', 'Розбій', '00ff88', NULL, NULL, true, false),
(4, NULL, 'uk_UA', 3, 'Торгівля людьми', 'Торгівля людьми', 'ffd900', NULL, NULL, true, false),
(5, NULL, 'uk_UA', 4, 'Згвалтування', 'Згвалтування', '3a10e3', NULL, NULL, true, false),
(6, NULL, 'uk_UA', 5, 'Корупція', 'Корупція', 'e66007', NULL, NULL, true, false),
(7, NULL, 'uk_UA', 6, 'Шахрайство', 'Шахрайство', 'd10fd1', NULL, NULL, true, false),
(8, NULL, 'uk_UA', 7, 'Грабіж', 'Грабіж', '77de1d', NULL, NULL, true, false),
(9, NULL, 'uk_UA', 8, 'Контрабанда', 'Контрабанда', '00ff2b', NULL, NULL, true, false),
(10, NULL, 'uk_UA', 9, 'Крадіжка', 'Крадіжка', 'd67513', NULL, NULL, true, false),
(11, NULL, 'uk_UA', 10, 'Хуліганство', 'Хуліганство', '07e8bb', NULL, NULL, true, false),
(12, 15, 'uk_UA', 12, 'Мітинг', 'Мітинг', 'd0e303', NULL, NULL, true, false),
(13, 15, 'uk_UA', 13, 'Масові безлади', 'Масові безлади', '7911bf', NULL, NULL, true, false),
(14, 15, 'uk_UA', 14, 'Акції протеста', 'Акції протеста', 'db5d14', NULL, NULL, true, false),
(15, NULL, 'uk_UA', 11, 'Масові заходи', 'Масові заходи', '286309', NULL, NULL, true, false),
(16, NULL, 'uk_UA', 15, 'ДТП', 'ДТП', '0f4ccf', NULL, NULL, true, false),
(17, 22, 'uk_UA', 19, 'Стихійне лихо', 'Стихійне лихо', '383621', NULL, NULL, true, false),
(18, 22, 'uk_UA', 17, 'Біологічного характеру', 'Біологічного характеру', '0b6100', NULL, NULL, true, false),
(19, NULL, 'uk_UA', 20, 'ЗЗС пов`язані з незаконним оббігом наркотиків', 'ЗЗС пов`язані з незаконним оббігом наркотиків', '561799', NULL, NULL, true, false),
(20, NULL, 'uk_UA', 21, 'Інше', 'Інше', '000000', NULL, NULL, true, false),
(21, 22, 'uk_UA', 18, 'Пожежа', 'Пожежа', 'c78f16', NULL, NULL, true, false),
(22, NULL, 'uk_UA', 16, 'Надзвичайні події', 'Надзвичайні події', '12c72a', NULL, NULL, true, false),
(23, NULL, 'uk_UA', 22, 'Розшук', 'Розшук', 'd911cf', NULL, NULL, true, false),
(24, 23, 'uk_UA', 23, 'Неповнолітні', 'Неповнолітні', '31e312', NULL, NULL, true, false),
(25, 23, 'uk_UA', 24, 'Безвісті зникші', 'Безвісті зникші', 'a1540b', NULL, NULL, true, false);